-- Auto-generated from schema-map-mysql.yaml (map@sha1:0D716345C0228A9FD8972A3D31574000D05317DB)
-- engine: mysql
-- table:  authors

CREATE TABLE IF NOT EXISTS authors (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  tenant_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(255) NOT NULL,
  name_ci VARCHAR(255) GENERATED ALWAYS AS (LOWER(name)) STORED,
  slug VARCHAR(255) NOT NULL,
  slug_ci VARCHAR(255) GENERATED ALWAYS AS (LOWER(slug)) STORED,
  bio TEXT NULL,
  photo_url VARCHAR(255) NULL,
  story LONGTEXT NULL,
  books_count INT NOT NULL DEFAULT 0,
  ratings_count INT NOT NULL DEFAULT 0,
  rating_sum INT NOT NULL DEFAULT 0,
  avg_rating DECIMAL(3,2) NULL DEFAULT NULL,
  last_rating_at DATETIME(6) NULL,
  created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  version INT UNSIGNED NOT NULL DEFAULT 0,
  deleted_at DATETIME(6) NULL,
  is_live TINYINT(1) GENERATED ALWAYS AS (deleted_at IS NULL) STORED,
  INDEX idx_authors_avg_rating (avg_rating),
  INDEX idx_authors_books_count (books_count)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;
